### ISSUE TITLE
Multiple display support

### ISSUE THREAD

**Issue by frontoge** [veselink1/fancywm-issues#1]
**Is your feature request related to a problem? Please describe.**
Currently _as far as I am aware_ the tiling only applies to one monitor. Which makes it feel like I am only utilizing half the space I could be (I can still use the other monitor but the tiling isn't there)

**Describe the solution you'd like**
It would be nice to have this supported on displays other than the primary/default. Along with key binds to move the windows/tiles across displays as they are configured in the windows display settings.

**Describe alternatives you've considered**
Configuring the layout of the displays in the settings of the application would also be more than sufficient. 

**Additional context**
![image](https://user-images.githubusercontent.com/54252905/114476707-be18e880-9bc8-11eb-865c-5e52c80b2bee.png)
Example of the tiling being applied on the right _main display_ but not on the left _secondary display_

**Comment by veselink1** [comment]
Hi @frontoge, thanks for opening a feature request!

Multiple display support is definitely something that is on my radar and being worked on. Progress is slow, because I do not own a second monitor. 

Most of the groundwork is laid already, but questions remain about the UX and possible configuration options - I might follow up with that here. 

The display configuration will likely be the one set in Windows Display Settings - that is what the backend (WinMan) supports. 

I am planning to focus more on this for the release after the next one, so stay tuned.

**Comment by seffyroff** [comment]
I came here to add the same issue, thanks for reporting it @frontoge.  I'm ready to test once this is available in a build.

**Comment by veselink1** [comment]
FancyWM v1.5.7 includes some very basic multi-display support. The feature is experimental and needs to be enabled from Settings > Displays. FancyWM needs to be restarted after this setting is changed. 

The only thing that is supported at this point is moving windows between displays with the mouse. Keybindings will be added later. The windows should attach to the layout of the display they are on when moved.

What doesn't work:
- Connecting, disconnecting and changing "projection" settings (duplicate, extend, etc.) causes crashes
- Moving floating windows between displays causes them to lose the floating mode setting

If FancyWM fails to start properly after enabling the experimental multi-display support, the setting will need to be reverted manually by changing the value of `ExperimentalMultiMonitorSupport` in `%appdata%\FancyWM\settings.json` to `false`.

**Comment by veselink1** [comment]
Multi-display support is much more stable as of v1.11.0 and is now enabled by default.

**Comment by llinfeng** [comment]
@veselink1 Please advise if I missed it - for App version 2.6.6.0, how to move one window to the next monitor with a keyboard shortcut?

Assuming it is not implemented for now, I find DisplayFusion doing the trick. As specified in the following screenshot, I use:
* `Ctrl+Win+L` to move the window to the monitor on the right, and
* `Ctrl+Win+H` to move the window to the monitor on the left

![image](https://user-images.githubusercontent.com/5890407/166329330-6a3146f9-ef02-4861-bde5-b085c7e14845.png)

When moved, depending on whether there are existing windows in the destination monitor, the window moved through DisplayFusion shall snap right in, or take up the full display by occupying the "invisible top-level panel" (language borrowed from the Help tab in FancyWM Settings). 

**Caveat**: only non-maximized windows moved through the shortcut are "managed" by FancyWM in the destination monitor. If a window has been maximized previously, restoring it and moving it through DisplayFusion won't necessarily get it to join the "panel" in the destination display. In this case, forcing the window to _float_ will join it to the panel in the destination display. Afterwards, moving the same window with DisplayFusion shortcuts gets the job done as expected.

----

For more context, I use AutoHotKey to toggle the Maximize/Windowed mode for the active window using `Win + Enter` key.
```
; Source: www.autohotkey.com/board/topic/16755-help-toggle-maximizerestore-with-same-hotkey/?p=108614
#Enter:: 
   WinGet MX, MinMax, A
   If MX
        WinRestore A
   Else WinMaximize A
return
```

**Comment by llinfeng** [comment]
One follow-up question - across multiple monitors, may there be a mode to quickly select a window by some visual cue? @veselink1 I read from [your previous post](https://github.com/FancyWM/fancywm-issues/issues/1#issuecomment-818499299) that you are interested in comments about UX implementations. Here is an example:

In Vim, [vim-choosewin](https://github.com/t9md/vim-choosewin) implements a "pane-selector" interface. Upon summoning such "pane-selector", letters are drawn specifically for each visible pane as below. Typing the letter brings the cursor to the corresponding "pane". (In Vim, a "pane" is similar to a Window managed by FancyWM.)
![image](https://raw.githubusercontent.com/t9md/t9md/1675510eaa1b789aeffbc49c1ae3b1e8e7dceabe/img/vim-choosewin.gif)

**Comment by sim590** [comment]
As @llinfeng seems to point out, moving windows to other displays is not feasible? May be there should be an issue opened to track this. It seems to me that using the keybinds to focus a window to the right when the focus is on the rightmost window and that there is a window on a display on the right, the focus should go on the other window on the right, but it doesn't. I really have to "focus the other display" first. Since displays are always either left, right up or down wards, I would expect the keybinds I'm talking about to work accross displays.

**Comment by llinfeng** [comment]
>As @llinfeng seems to point out, moving windows to other displays with the keyboard is not feasible?

In its current state, FancyWM does not support multiple-monitor setups. Within itself, it cannot move one window from one monitor to the next using shortcuts (or key-combinations). DisplayFusion is useful when it comes to moving windows around.

**Comment by veselink1** [comment]
@sim590 @llinfeng 
Moving windows between monitors is supported but the keybindings are not configurable in the UI in the latest version. 
https://github.com/FancyWM/fancywm-issues/blob/main/CHANGELOG.md#v280

**Comment by veselink1** [comment]
The enumeration of monitors is based on the internal device names assigned by Windows and should be consistent with the output of `mstsc /l`, but is different from what is shown in Settings.

**Comment by llinfeng** [comment]
Great, then, when `mstsc /l` returns the following list, does it mean `MoveToDisplay1` will stop working, and I need to use `MoveToDisplay4` instead?

![image](https://user-images.githubusercontent.com/5890407/191098544-649000ab-65b9-4257-a12f-8af78004a2d2.png)

**Comment by jfinken** [comment]
Commenting here, but happy to open a new issue too if/as appropriate.

Is there a way to _restrict_ tiling windows to a given display?  Often when I unlock Win11, a particular Desktop will re-tile to Display 1 (laptop), when I want _all_ windows to simply be restricted to Display 2 (external monitor) only.  

I see the `FancyWM Settings \ General \ Displays \ Enable tiling on all connected displays` On/Off.  But if off, then how to restrict to specific Display for example?  Thank you.
