### ISSUE TITLE
Ordering of windows not persistent

### ISSUE THREAD

**Issue by mataslib** [veselink1/fancywm-issues#6]
**Describe the bug**
Ordering of windows changes on virtual dekstop switch (is not persistent)

**To Reproduce**
1. Open chrome, open vscode
2. Change order of windows
3. Switch to another desktop
4. Switch back
5. Windows ordering is not preserved

**Expected behavior**
Order doesn't change with switching vdesktops

**Screenshots**

**Desktop (please complete the following information):**
W11 21h2 22000.282

**Comment by veselink1** [comment]
Fixed in FancyWM 1.8.3.
