### ISSUE TITLE
Panels not persistent

### ISSUE THREAD

**Issue by mataslib** [veselink1/fancywm-issues#7]
**Describe the bug**
Panels are destroyed on vdesktop switch.

**To Reproduce**
1. Open chrome
2. Create stack panel
3. Swtich to another vdesktop
4. Switch vdesktop back 
5. Panels are lost

**Expected behavior**
Panels are persistent upon vdesktop switch

**Desktop (please complete the following information):**
W11 21h2 22000.282

**Comment by veselink1** [comment]
Fixed in FancyWM 1.8.3.
