### ISSUE TITLE
Support for Windows 11's new virtual desktop manager

### ISSUE THREAD

**Issue by veselink1** [veselink1/fancywm-issues#8]
**Is your feature request related to a problem? Please describe.**
FancyWM is not able to interface with Windows 11's updated desktop manager. This means that upon switching to a virtual desktop, all windows are tiling layouts are destroyed, windows ordering is lost. 

**Describe the solution you'd like**
FancyWM should support Windows 11 seamlessly. If possible, this should be implemented in the Windows backend of WinMan (https://github.com/veselink1/winman-windows). 

**Additional context**
- #7
- #6

**Comment by veselink1** [comment]
FancyWM 1.8.3 ships with an updated winman-windows package which has Windows 11 support (Fixes #6, #7).

**Comment by mataslib** [comment]
Thanks! That was fast 👍
