### ISSUE TITLE
Apps opened as administrator are not managed by FancyWM

### ISSUE THREAD

**Issue by mataslib** [veselink1/fancywm-issues#9]
**Describe the bug**
I've noticed that since I allowed for vscode "run this program as an administrator" (properties, compatability tab), FancyWM stopped managing it's windows. Shift+win is ignored, auto-tiling doesn't apply.

**To Reproduce**
1. Allow "run this program as an administrator" for vscode
2. Launch vscode

**Expected behavior**
FancyWM would manage windows regardless of privilege mode

**Screenshots**
![image](https://user-images.githubusercontent.com/5154014/144017549-6f8eff4f-ee3d-4445-897d-e0c802bbf9b7.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Version 21H2 22000.348

**Comment by veselink1** [comment]
Hi, thanks for opening this issue. 

Unprivileged applications cannot access windows from privileged applications on Windows. If you want FancyWM to manage your VSCode window, you will need to start FancyWM as an administrator as well. This is how the OS was designed. You should be able to right-click on FancyWM in the Start menu and "Run as administrator".

Windows  runs startup applications as the current user, therefore, if you are using the "Run Automatically at System Startup" from the FancyWM Settings and you want to enable tiling for privileged processes, you will need to 1. Quit FancyWM, 2. Run as administrator. Please, tell me whether this works for you.

**Comment by veselink1** [comment]
I have opened a feature request to make FancyWM startup as administrator on logon. This will likely become available in the new release, whenever that happens.

Until then, here is the manual way of settings this up:
1. Task Scheduler
2. Create basic task (on the right)
3. Name: "FancyWM", click [Next]
4. Select "When I log on", click [Next]
5. Select "Start a program", click [Next]
6. Program/script: "%LOCALAPPDATA%\Microsoft\WindowsApps\FancyWM.exe"
7. Select "Open the Properties dialog for this task when I click Finish", click [Finish]
8. In General, select "Run with highest privileges"
9. In Settings, deselect "Stop the task if it runs longer than"
10. Click [OK] to close this dialog
11. Deselect "Run Automatically at System Startup" from the FancyWM Settings

FancyWM should now run as administrator when you log in.

**Comment by mataslib** [comment]
Oh my, I'm so dumb, that makes sense... And it works as you say. I just wanted to suggest opt-in for running as admin on startup (you already overrun me). 👍 Thanks for instructions.

**Comment by veselink1** [comment]
No worries, this is why we have this issue tracker. 
I will close this now, progress for running as admin on startup is tracked by #10.
